version: '2'
services:
    agatha-app:
        image: agatha
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://agatha-mysql:3306/agatha?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    agatha-mysql:
        extends:
            file: mysql.yml
            service: agatha-mysql
